using TMPro;
using UnityEngine;
using Slider = UnityEngine.UI.Slider;

public class MainHUDController : MonoBehaviour  {
    
    [SerializeField] private TextMeshProUGUI _moneyText;
    [SerializeField] private TextMeshProUGUI _timeText;
    [SerializeField] private Slider _charismaSlider;
    public void SetMoneyText(float money) {
        _moneyText.text = money + "$";
    }

    public void SetTime(int hour) {
        _timeText.text = "Current Time: " + hour.ToString() + ":00";
    }
    
    public void SetCharisma(int charisma) {
        //map 0-100 to 0-1
        _charismaSlider.value = charisma / 100f;
    }
    
}
